# Generated by Django 5.0.6 on 2024-07-09 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
                ('max_views', models.IntegerField(default=1)),
            ],
        ),
    ]
