version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
